LOAD DATA LOCAL INFILE '/scratch/DATABASE/affyProbeset.txt' INTO TABLE affyprobeset LINES TERMINATED BY '\n' IGNORE 1 LINES;


LOAD DATA LOCAL INFILE '/scratch/DATABASE/probesetID_to_rsid.txt' INTO TABLE map_probsetID_rsid LINES TERMINATED BY '\n' IGNORE 1 LINES;


LOAD DATA LOCAL INFILE '/scratch/DATABASE/birdSeedCall.txt' INTO TABLE birdseedcall LINES TERMINATED BY '\n' IGNORE 1 LINES;


LOAD DATA LOCAL INFILE '/scratch/DATABASE/hg19_snp147.txt' INTO TABLE snp147 LINES TERMINATED BY '\n' ;

